baseURL = 'http://blog.mjurtz.com/'
languageCode = 'de-DE'
title = 'Marcel Jurtz'
theme = "hyde"

[Menus]
  main = [
      
  ]
  
[params]
  description = "Notes and thoughts on software development"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true