baseURL = 'http://blog.mjurtz.com/'
languageCode = 'de-DE'
title = 'Marcel Jurtz'
theme = "hyde"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/MarcelJurtz/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/marcel-jurtz-302b881b1/"}
  ]
  
[params]
  description = "Notes and thoughts on software development"