baseURL: https://mjurtz.com/
languageCode: en-us
title: Marcel Jurtz
theme: "PaperMod"
pagination: 
    pagerSize: 5

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Being interested in software, but also endurance sports and general fitness, I use this site to document my findings in the intersections of both worlds."
    author: "Marcel Jurtz"
    defaultTheme: dark
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: false
    # comments: false
    images: ["papermod-cover.png"]

    showPostsOnMainPage: false
    homeInfoParams:
        Title: "Marcel Jurtz"
        Content: >
            Hey! Schön, dass du zu mir gefunden hast. Ich bin Marcel und lebe in Überlingen am Bodensee. Seit 2014 bin ich in der Softwareentwicklung unterwegs und seit 2020 auch selbstständig aktiv. 2025 habe ich den Schritt zur Vollzeit-Selbstständigkeit gewagt und dort hauptsächlich im Bereich der Webentwicklung tätig.
            <br/><br/>Du bist auf der Suche nach einem Entwickler für dein Projekt oder zur Ergänzung deines bestehenden Teams? Melde dich gerne unverbindlich bei mir und ich unterstütze dich gerne bei Entwurf, Umsetzung und Wartung deiner Anwendung oder Website. Ich freue mich auf deine Kontaktaufnahme!
            <br/><br/>Bist du aus dem Fitness-Bereich auf mich aufmerksam geworden? Dann wirst du <a href="https://www.fitness.mjurtz.com">hier</a> fündig!
    socialIcons:
        - name: email
          url: "mailto:marcel@mjurtz.com"
        - name: phone
          url: "tel:+4917622773010"
        - name: linkedin
          url: "https://www.linkedin.com/in/marcel-jurtz/"
        - name: github
          url: "https://github.com/marceljurtz"
        - name: instagram
          url: "https://instagram.com/marceljurtz"
        - name: strava
          url: "https://www.strava.com/athletes/33542098"
        - name: youtube
          url: "https://www.youtube.com/@marceljurtz"

    assets:
        disableHLJS: true
    
    label:
        text: mjurtz.com
        icon: /assets/logo-only.svg
        iconHeight: 25
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    #goldmark:
    #    renderer:
    #        unsafe: true
    highlight:
        # noClasses: false
        # anchorLineNos: true
        codeFences: true
        guessSyntax: false
        lineNos: true
        style: monokai
    goldmark:
        renderer:
            unsafe: true


privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true